/**
 * Subtitle-related type definitions
 */

export interface SubtitleTimestamp {
  startTime: number; // milliseconds
  endTime: number; // milliseconds
  text: string;
}

export interface Subtitle {
  id: string;
  videoId: string;
  language: string; // ISO 639-1 code
  languageName: string;
  format: 'srt' | 'vtt' | 'ass' | 'json';
  content: string;
  isAutoGenerated: boolean;
  timestamps?: SubtitleTimestamp[];
}

export interface SubtitleInfo {
  language: string;
  languageName: string;
  isAutoGenerated: boolean;
  formats: string[];
}

export interface BilingualSubtitleConfig {
  primaryLanguage: string;
  secondaryLanguage: string;
  layout: 'stacked' | 'side_by_side';
  primaryPosition?: 'top' | 'bottom';
  secondaryPosition?: 'top' | 'bottom';
  styling?: SubtitleStyling;
}

export interface SubtitleStyling {
  primaryFontSize?: number;
  secondaryFontSize?: number;
  primaryColor?: string;
  secondaryColor?: string;
  fontFamily?: string;
  outline?: boolean;
  shadow?: boolean;
  backgroundColor?: string;
  backgroundOpacity?: number;
}

export interface SubtitleGenerationOptions {
  language?: string;
  model?: 'tiny' | 'base' | 'small' | 'medium' | 'large';
  translate?: boolean;
  detectLanguage?: boolean;
  task?: 'transcribe' | 'translate';
  outputFormat?: 'srt' | 'vtt' | 'json';
}

export interface EmbedSubtitleOptions {
  primarySubtitle: Subtitle;
  secondarySubtitle?: Subtitle;
  layout: 'stacked' | 'side_by_side';
  styling?: SubtitleStyling;
  outputPath: string;
  hardSub?: boolean; // Burn subtitles into video
}